### ISSUE TITLE
Home page polish

### ISSUE THREAD

**Issue by aga11313** [jina-ai/website#62]
Make sure Home page is matching the designs perfectly and provides a good UX (except for missing components) on ALL machines (MAC, Windows)

- [x] fonts
- [ ] Windows weird displaying things
- [ ] demo loading
- [x] subscribe bug
- [ ] add banner
- [x] add star count
- [ ] navbar hovering
![image](https://user-images.githubusercontent.com/23415764/124722991-e172db80-df0a-11eb-8bbf-9d3c16187557.png)
- [x] code block font
- [x] hover effects on buttons
![image](https://user-images.githubusercontent.com/23415764/124726700-48de5a80-df0e-11eb-95b8-2a065d9b6259.png)
- [ ] code block font colours
- [ ] code block close, minimize and window buttons

**Comment by Roshanjossey** [comment]
Na stronie głównej nie było języka polskiego.

**Comment by aga11313** [comment]
> Na stronie głównej nie było języka polskiego.

Crap, was meant to name this ticket Home page english
