### ISSUE TITLE
Polish the learn page

### ISSUE THREAD

**Issue by aga11313** [jina-ai/website#73]
Make sure:

- all the components are present on the page
- the text on the page is all matching the Figma
- the designs match the Figma EXACTLY

**Comment by Roshanjossey** [comment]
It looks like we have finished the two sections in learn page. @pswu11, please review and point out any polishing we need to do.

**Comment by pswu11** [comment]
Polishing
- inconsistent size and position of the header in comparison to other pages, maybe some style issues 
- the button looks off, it should looks like the button on career, about, or contribution page
