### ISSUE TITLE
Remove address and phone number in Footer

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/website#82]
![image](https://user-images.githubusercontent.com/8488446/125181000-28551f80-e1f0-11eb-8c2f-db773010c14b.png)

The address and phone number in the footer is wrong. 

You can find documentation on how to update copy in the documentation here https://github.com/jina-ai/website/blob/9bd7698346cbec86363e09a56de182c957ff3a0d/README.md

**Comment by pswu11** [comment]
@Roshanjossey Is there a way for me to wrap the text for the company address? 
So it looks like 
```
Karl-Liebknecht-Str. 5
10178 Berlin
Germany
```
OR
```
Karl-Liebknecht-Str. 5
10178 Berlin, Germany
```

instead of in one line?

**Comment by Roshanjossey** [comment]
Sure. You can use multiline string in javascript.
Instead of
```
'
Karl-Liebknecht Str. 5
10178 Berlin
Germany
'
```
do
```
`
Karl-Liebknecht Str. 5
10178 Berlin
Germany
`
```
with backticks

**Comment by pswu11** [comment]
@Roshanjossey 
Thanks a lot! With the latest meeting I had with the management, we are taking out the address and phone number information from the footer. Still, a nice lesson learned :)

**Comment by Roshanjossey** [comment]
Yeah, I read it on slack. I'll change the issue to updating footer to new designs

**Comment by pswu11** [comment]
This should be how it looks like after the removing address and phone number



![Screenshot from 2021-07-14 18-04-44](https://user-images.githubusercontent.com/48913707/125654816-c128dc3b-2e9c-4a71-8c2a-9b2f06abd337.png)
