### ISSUE TITLE
add description section to all nav-bar drop downs 

### ISSUE THREAD

**Issue by pswu11** [jina-ai/website#98]
No need to update the text exactly, just make the description sections available as shown below

![Screenshot from 2021-07-20 22-32-06](https://user-images.githubusercontent.com/48913707/126391697-0e0e6b2b-ed81-46d2-ae5d-4ef2177228b5.png)

**Comment by Roshanjossey** [comment]
Data for dropdown is in https://github.com/jina-ai/website/blob/main/src/template/NavBar.tsx#L8

This issue will involve adding rest of the copy needed in websiteCopyStrings.ts and updating the array in the file linked above with the corresponding copy.
